#!/usr/bin/env python3
"""
Script to embed HTML files into C++ header as string literals.
Converts data/index.html into src/html_template.h
"""

import os
import sys
from pathlib import Path

def main():
    # Get the project root directory (parent of scripts/)
    script_dir = Path(__file__).parent
    project_root = script_dir.parent

    # Define file paths
    data_dir = project_root / "data"
    src_dir = project_root / "src"

    html_file = data_dir / "index.html"
    output_file = src_dir / "html_template.h"

    # Check if HTML file exists
    if not html_file.exists():
        print(f"Error: Required file not found: {html_file}")
        sys.exit(1)

    try:
        # Read HTML file
        with open(html_file, 'r', encoding='utf-8') as f:
            html_content = f.read()

        # Hardcoded prefix and suffix
        prefix_content = 'const char* htmlContent = R"HTML(\n'
        suffix_content = ')HTML";\n'

        # Combine content
        combined_content = prefix_content + html_content + suffix_content

        # Write to output file
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("#pragma once\n\n")
            f.write("// This file is auto-generated by scripts/embed_html.py\n")
            f.write("// Do not edit manually - changes will be overwritten\n\n")
            f.write(combined_content)

        print(f"Successfully generated {output_file}")

    except Exception as e:
        print(f"Error generating header file: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()